services:
  app:
    build: .
    container_name: weather-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/weatherdb
      - WEATHER_API_URL=https://api.openweathermap.org
      - WEATHER_API_APP_ID=${WEATHER_API_APP_ID}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb
    networks:
      - weather-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - weather-network

volumes:
  mongodb_data:

networks:
  weather-network:
    driver: bridge