version: '3.8'

services:
  app:
    build: .
    container_name: weather-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/weatherdb
      - WEATHER_API_URL=https://api.openweathermap.org
      - WEATHER_API_APP_ID=${WEATHER_API_APP_ID}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - weather-network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    command: mongod --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - weather-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  weather-network:
    driver: bridge